# Generated by Django 5.0.4 on 2024-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='punlished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
